AWSTemplateFormatVersion: '2010-09-09'
Description: A simple EC2 creation using CloudFormation
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-078f95be0757084a3 # Amazon Linux 2 AMI (HVM), SSD Volume Type
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup

Outputs:
  InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref MyEC2Instance 
      